#!/usr/bin/env python3
"""KaviTV relay v2.0 — hardened rebuild. No duct tape.

What changed from v1.x:
  1. Structured logging to rotating files (was: log_message no-op).
  2. Timeline manager: cached, hot-reloaded on mtime change, schema-
     validated on every load (was: re-read + parsed per request, no validation).
  3. ffmpeg supervisor: per-connection deadline, stall detection (no bytes
     for STALL_TIMEOUT mid-stream kills the process), SIGTERM -> 5s ->
     SIGKILL escalation with proc.wait() reaping (no zombies).
     (was: first-byte timeout only, terminate-or-kill without reaping.)
  4. Slate fallback: if the source fails after retries, serve a generated
     "KAVITV - PLEASE STANDBY" slate via ffmpeg testsrc instead of HTTP 502,
     so the tuner never sees an error (was: 502, tuner shows error).
  5. Deep health check at /api/deep-health: validates timeline, ffmpeg,
     and actually probes that a stream can start (was: /api/health only
     reported static facts; a wedged relay still returned ok:true).
  6. Startup validation: ffmpeg exists, timeline valid, emby.key readable,
     port free — exits with distinct codes and a clear log line otherwise.
  7. Child-process registry: every spawned ffmpeg PID tracked; on shutdown
     all children are reaped (was: orphaned ffmpeg processes possible).

Architecture (unchanged from v1):
  The relay OWNS ffmpeg. Emby is a dumb byte source via
  /emby/Videos/<id>/stream?static=true. Per tune-in the relay spawns
  ffmpeg with a SINGLE input -ss, stream-copy to MPEG-TS, pipes stdout.

Endpoints:
  GET /kavitv/live/<slug>[.m3u8] -> 200 video/mp2t, live MPEG-TS
  GET /api/health                 -> {ok, version, ...} (lightweight)
  GET /api/deep-health            -> {ok, checks:{...}} (for watchdogs)

Config (C:\\Users\\sethr\\kavitv\\config\\):
  emby.key       API key (never logged)
  timeline.json  generated by generate.py (hot-reloaded)

Logs: C:\\Users\\sethr\\kavitv\\logs\\relay.log (10 MB rotation x5)

Run:  python relay.py [--port 8100]
      (production: via NSSM service, see relay-deploy.md)
"""

import json
import logging
import logging.handlers
import os
import queue
import subprocess
import sys
import threading
import time
import urllib.parse
from datetime import datetime, timezone
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

# --------------------------------------------------------------------------
# Configuration
# --------------------------------------------------------------------------

BASE_DIR = r"C:\Users\sethr\kavitv"
CONFIG_DIR = os.path.join(BASE_DIR, "config")
LOG_DIR = os.path.join(BASE_DIR, "logs")
KEY_FILE = os.path.join(CONFIG_DIR, "emby.key")
TIMELINE_FILE = os.path.join(CONFIG_DIR, "timeline.json")
FFMPEG = r"C:\Users\sethr\AppData\Roaming\Emby-Server\system\ffmpeg.exe"
EMBY = "http://127.0.0.1:8096"  # relay runs ON the Emby box
VERSION = "2.0.0"

CHANNELS = {
    "horror": "kavitv.horror",
    "experimental": "kavitv.experimental",
    "independent": "kavitv.independent",
}

# Timing (seconds)
FIRST_BYTE_TIMEOUT = 30   # max wait for ffmpeg's first output byte
STALL_TIMEOUT = 15         # max gap between bytes mid-stream before kill
RETRY_BACKOFF = [0, 2, 5]  # seconds between source attempts
SHUTDOWN_TIMEOUT = 10     # max wait for children on shutdown

CHUNK = 65536
SLATE_DURATION = 30       # slate loops; client disconnects when done


# --------------------------------------------------------------------------
# Logging
# --------------------------------------------------------------------------

def setup_logging():
    os.makedirs(LOG_DIR, exist_ok=True)
    logger = logging.getLogger("kavitv")
    logger.setLevel(logging.INFO)
    fmt = logging.Formatter(
        "%(asctime)s [%(levelname)s] %(name)s: %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S")

    fh = logging.handlers.RotatingFileHandler(
        os.path.join(LOG_DIR, "relay.log"),
        maxBytes=10 * 1024 * 1024, backupCount=5, encoding="utf-8")
    fh.setFormatter(fmt)
    logger.addHandler(fh)

    # Console when run interactively (not under pythonw/NSSM)
    if sys.stdout and not sys.stdout.closed:
        try:
            ch = logging.StreamHandler(sys.stdout)
            ch.setFormatter(fmt)
            logger.addHandler(ch)
        except Exception:
            pass
    return logger


log = setup_logging()


# --------------------------------------------------------------------------
# Child-process registry (no orphaned ffmpeg)
# --------------------------------------------------------------------------

class ChildRegistry:
    """Tracks every spawned ffmpeg so shutdown reaps them all."""

    def __init__(self):
        self._lock = threading.Lock()
        self._procs = set()

    def add(self, proc):
        with self._lock:
            self._procs.add(proc)

    def discard(self, proc):
        with self._lock:
            self._procs.discard(proc)

    def kill_all(self):
        with self._lock:
            procs = list(self._procs)
        for proc in procs:
            reap_process(proc, "shutdown")
        with self._lock:
            self._procs.clear()


CHILDREN = ChildRegistry()


def reap_process(proc, reason=""):
    """SIGTERM -> wait 5s -> SIGKILL -> wait. Never leaves a zombie."""
    if proc is None or proc.poll() is not None:
        return
    try:
        proc.terminate()
    except Exception:
        pass
    try:
        proc.wait(timeout=5)
        log.debug("reaped pid=%s reason=%s (terminate)", proc.pid, reason)
        return
    except Exception:
        pass
    try:
        proc.kill()
    except Exception:
        pass
    try:
        proc.wait(timeout=5)
        log.warning("force-killed pid=%s reason=%s", proc.pid, reason)
    except Exception:
        log.error("could not reap pid=%s reason=%s", proc.pid, reason)


# --------------------------------------------------------------------------
# Timeline manager (cached, hot-reloaded, validated)
# --------------------------------------------------------------------------

class TimelineManager:
    def __init__(self, path):
        self.path = path
        self._lock = threading.Lock()
        self._data = None
        self._mtime = 0

    def _validate(self, tl):
        if not isinstance(tl, dict):
            raise ValueError("timeline root must be an object")
        channels = tl.get("channels")
        if not isinstance(channels, dict) or not channels:
            raise ValueError("timeline.channels missing or empty")
        for cid, ch in channels.items():
            slots = ch.get("slots")
            if not isinstance(slots, list) or not slots:
                raise ValueError(f"channel {cid}: no slots")
            for s in slots:
                for field in ("start", "end", "title", "emby_id"):
                    if field not in s:
                        raise ValueError(
                            f"channel {cid}: slot missing {field}")
                # start/end must parse
                datetime.fromisoformat(s["start"])
                datetime.fromisoformat(s["end"])
        return tl

    def get(self):
        """Return cached timeline, reloading if the file changed."""
        try:
            mtime = os.path.getmtime(self.path)
        except OSError as e:
            raise FileNotFoundError(f"timeline.json unreadable: {e}")
        with self._lock:
            if self._data is not None and mtime == self._mtime:
                return self._data
            with open(self.path, encoding="utf-8") as f:
                raw = json.load(f)
            self._data = self._validate(raw)
            self._mtime = mtime
            n_slots = sum(len(c["slots"])
                          for c in self._data["channels"].values())
            log.info("timeline loaded: %d channels, %d slots (mtime=%s)",
                     len(self._data["channels"]), n_slots, mtime)
            return self._data

    def invalidate(self):
        with self._lock:
            self._data = None


TIMELINE = TimelineManager(TIMELINE_FILE)


def current_program(timeline, cid):
    """(slot, offset_sec) for what's airing now on timeline channel `cid`."""
    slots = timeline["channels"][cid]["slots"]
    now = datetime.now(timezone.utc)
    lo, hi = 0, len(slots) - 1
    while lo <= hi:
        mid = (lo + hi) // 2
        s = datetime.fromisoformat(slots[mid]["start"])
        e = datetime.fromisoformat(slots[mid]["end"])
        if e <= now:
            lo = mid + 1
        elif s > now:
            hi = mid - 1
        else:
            if (e - now).total_seconds() < 10 and mid + 1 < len(slots):
                return slots[mid + 1], 0.0
            dur = (e - s).total_seconds()
            offset = max(0.0, min((now - s).total_seconds(), dur - 10.0))
            return slots[mid], offset
    return None, 0.0


def load_key():
    with open(KEY_FILE, encoding="utf-8") as f:
        return f.read().strip()


def static_url(item_id, api_key):
    q = urllib.parse.urlencode({"static": "true", "api_key": api_key})
    return f"{EMBY}/emby/Videos/{item_id}/stream?{q}"


# --------------------------------------------------------------------------
# ffmpeg supervision
# --------------------------------------------------------------------------

def spawn_ffmpeg(src_url, offset_sec):
    """Start ffmpeg: input-seek, stream-copy, MPEG-TS to stdout pipe."""
    cmd = [
        FFMPEG,
        "-hide_banner", "-nostats", "-loglevel", "error",
        "-fflags", "+genpts+discardcorrupt+igndts",
        "-ss", f"{offset_sec:.1f}",
        "-i", src_url,
        "-map", "0:v:0", "-map", "0:a:0",
        "-c:v", "copy", "-c:a", "copy",
        # -output_ts_offset keeps timestamps sane after seek without the
        # decode errors that -copyts -start_at_zero produced (2026-10-04).
        "-output_ts_offset", "0",
        "-f", "mpegts",
        "-mpegts_flags", "resend_headers",
        "-flush_packets", "1",
        "pipe:1",
    ]
    proc = subprocess.Popen(
        cmd, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL,
        stdin=subprocess.DEVNULL)
    CHILDREN.add(proc)
    return proc


def spawn_slate(text="KAVITV - PLEASE STANDBY"):
    """Generate a slate: test pattern + tone, as MPEG-TS to stdout.

    Used when the real source is unavailable so the tuner never sees
    an HTTP error mid-guide.
    """
    cmd = [
        FFMPEG,
        "-hide_banner", "-nostats", "-loglevel", "error",
        "-f", "lavfi", "-i",
        f"testsrc2=size=1280x720:rate=30",
        "-f", "lavfi", "-i",
        "sine=frequency=440:sample_rate=48000",
        "-vf",
        f"drawtext=text='{text}':fontcolor=white:fontsize=48:"
        "x=(w-text_w)/2:y=(h-text_h)/2",
        "-c:v", "libx264", "-preset", "ultrafast", "-tune", "zerolatency",
        "-c:a", "aac",
        "-f", "mpegts", "-flush_packets", "1",
        "pipe:1",
    ]
    proc = subprocess.Popen(
        cmd, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL,
        stdin=subprocess.DEVNULL)
    CHILDREN.add(proc)
    return proc


class StreamPump:
    """Pumps ffmpeg stdout through a queue with stall detection.

    Windows has no select() on pipes, so a reader thread feeds a queue
    and the consumer applies timeouts. Tracks bytes + last-byte time so
    a silently-stalled ffmpeg (connected but no frames) gets killed.
    """

    def __init__(self, proc, label=""):
        self.proc = proc
        self.label = label
        self.q = queue.Queue()
        self.bytes_out = 0
        self._stop = threading.Event()
        self._thread = threading.Thread(target=self._pump, daemon=True,
                                        name=f"pump-{proc.pid}")
        self._thread.start()

    def _pump(self):
        try:
            while not self._stop.is_set():
                chunk = self.proc.stdout.read(CHUNK)
                self.q.put((chunk if chunk else None, time.monotonic()))
                if not chunk:
                    break
        except Exception as e:  # noqa: BLE001
            self.q.put((e, time.monotonic()))

    def get(self, timeout):
        """Return (chunk, timestamp). chunk None => EOF. Raises on timeout."""
        try:
            chunk, ts = self.q.get(timeout=timeout)
        except queue.Empty:
            raise TimeoutError(f"[{self.label}] no bytes for {timeout}s")
        if isinstance(chunk, Exception):
            raise RuntimeError(f"[{self.label}] pump error: {chunk}")
        if chunk:
            self.bytes_out += len(chunk)
        return chunk

    def close(self):
        self._stop.set()
        reap_process(self.proc, f"pump-close {self.label}")
        CHILDREN.discard(self.proc)


def stream_ffmpeg_to_client(handler, proc, label):
    """Pipe a supervised ffmpeg's MPEG-TS to the HTTP client.

    Raises TimeoutError if the first byte is late or the stream stalls.
    Broken pipes (tuner went away) are normal and swallowed.
    """
    pump = StreamPump(proc, label)
    try:
        first = pump.get(FIRST_BYTE_TIMEOUT)
        if first is None:
            raise RuntimeError(f"[{label}] ffmpeg exited with no output")
        handler.send_response(200)
        handler.send_header("Content-Type", "video/mp2t")
        handler.send_header("Cache-Control", "no-cache")
        handler.end_headers()
        handler.wfile.write(first)
        handler.wfile.flush()
        log.info("[%s] streaming started (pid=%s)", label, proc.pid)
        while True:
            chunk = pump.get(STALL_TIMEOUT)
            if chunk is None:
                log.info("[%s] ffmpeg EOF after %d bytes",
                         label, pump.bytes_out)
                break
            handler.wfile.write(chunk)
            handler.wfile.flush()
    except (BrokenPipeError, ConnectionResetError):
        log.info("[%s] client disconnected after %d bytes",
                 label, pump.bytes_out)
    finally:
        pump.close()


# --------------------------------------------------------------------------
# HTTP handler
# --------------------------------------------------------------------------

class Handler(BaseHTTPRequestHandler):
    server_version = "KaviTV-Relay/2.0"

    def log_message(self, *a):
        pass  # we use structured logging

    def _json(self, code, obj):
        body = json.dumps(obj).encode()
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _now_map(self, tl):
        out = {}
        for slug, cid in CHANNELS.items():
            try:
                slot, off = current_program(tl, cid)
            except Exception:
                slot, off = None, 0.0
            out[slug] = {"title": slot["title"] if slot else None,
                         "offset_sec": round(off, 1)}
        return out

    def _serve_channel(self, slug):
        cid = CHANNELS.get(slug)
        if not cid:
            return self._json(400, {"error": "bad channel"})
        tl = TIMELINE.get()
        slot, offset_sec = current_program(tl, cid)
        if not slot:
            return self._json(404, {"error": "nothing scheduled"})
        item_id = slot["emby_id"]
        title = slot.get("title", "?")
        api_key = load_key()
        src = static_url(item_id, api_key)
        label = f"{slug}/{title}"

        # Attempt plan: computed offset, then offset 0, then slate.
        # Backoff between attempts so a flapping source doesn't hot-loop.
        attempts = []
        if offset_sec > 1.0:
            attempts.append(("seek", offset_sec))
        attempts.append(("start", 0.0))

        last_err = None
        for i, (kind, off) in enumerate(attempts):
            if i > 0:
                time.sleep(RETRY_BACKOFF[min(i, len(RETRY_BACKOFF) - 1)])
            log.info("[%s] attempt %d/%d (%s @ %.1fs)",
                     label, i + 1, len(attempts), kind, off)
            try:
                proc = spawn_ffmpeg(src, off)
                stream_ffmpeg_to_client(self, proc, label)
                return  # served successfully
            except (TimeoutError, RuntimeError) as e:
                last_err = e
                log.warning("[%s] attempt %d failed: %s", label, i + 1, e)
                continue

        # All source attempts failed: serve slate instead of HTTP 502.
        log.error("[%s] source failed after %d attempts (%s); serving slate",
                  label, len(attempts), last_err)
        try:
            proc = spawn_slate(f"KAVITV {slug.upper()} - PLEASE STANDBY")
            stream_ffmpeg_to_client(self, proc, f"slate-{slug}")
        except Exception as e:  # noqa: BLE001
            log.error("[slate-%s] failed too: %s", slug, e)
            self._json(502, {"error": "source and slate failed"})

    def do_GET(self):
        try:
            path = urllib.parse.urlsplit(self.path).path

            if path == "/api/health":
                try:
                    tl = TIMELINE.get()
                    now = self._now_map(tl)
                    gen = tl.get("generated_at")
                    chs = sorted(tl["channels"].keys())
                except Exception as e:  # noqa: BLE001
                    return self._json(503, {"ok": False, "error": str(e)[:200]})
                return self._json(200, {
                    "ok": True, "version": VERSION,
                    "ffmpeg": os.path.exists(FFMPEG),
                    "generated_at": gen,
                    "channels": chs, "now": now,
                })

            if path == "/api/deep-health":
                # For watchdogs: actually validate everything a stream needs.
                checks = {}
                try:
                    tl = TIMELINE.get()
                    checks["timeline"] = "ok"
                    for slug, cid in CHANNELS.items():
                        slot, _ = current_program(tl, cid)
                        checks[f"channel:{slug}"] = (
                            "ok" if slot else "nothing-scheduled")
                except Exception as e:  # noqa: BLE001
                    checks["timeline"] = f"FAIL: {e}"[:200]
                checks["ffmpeg"] = ("ok" if os.path.exists(FFMPEG)
                                    else "FAIL: missing")
                try:
                    key = load_key()
                    checks["emby_key"] = "ok" if key else "FAIL: empty"
                except Exception as e:  # noqa: BLE001
                    checks["emby_key"] = f"FAIL: {e}"[:200]
                ok = all(v == "ok" or v == "nothing-scheduled"
                         for v in checks.values())
                return self._json(200 if ok else 503,
                                  {"ok": ok, "version": VERSION,
                                   "checks": checks})

            # Back-compat: parent tooling probed /health (wrong path in v1
            # docs). Accept it and point at the right one.
            if path == "/health":
                return self._json(200, {"ok": True,
                                        "note": "use /api/health",
                                        "version": VERSION})

            if path.startswith("/kavitv/live/"):
                slug = path.split("/")[3].split(".")[0]
                self._serve_channel(slug)
                return

            return self._json(404, {"error": "not found"})
        except FileNotFoundError as e:
            log.error("config missing: %s", e)
            return self._json(503, {"error": "not configured",
                                    "detail": str(e)[:200]})
        except Exception as e:  # noqa: BLE001
            # Relay must never die on a bad request.
            log.exception("unhandled error serving %s", self.path)
            try:
                return self._json(500, {"error": "internal",
                                        "detail": str(e)[:200]})
            except Exception:
                pass


# --------------------------------------------------------------------------
# Startup validation + main
# --------------------------------------------------------------------------

def validate_startup():
    """Exit codes: 2=ffmpeg, 3=timeline, 4=emby.key, 5=port in use."""
    if not os.path.exists(FFMPEG):
        log.critical("FATAL: ffmpeg not found at %s", FFMPEG)
        return 2
    try:
        TIMELINE.get()
    except Exception as e:  # noqa: BLE001
        log.critical("FATAL: timeline invalid: %s", e)
        return 3
    try:
        key = load_key()
        if not key:
            raise ValueError("empty")
    except Exception as e:  # noqa: BLE001
        log.critical("FATAL: emby.key unreadable: %s", e)
        return 4
    import socket
    s = socket.socket()
    try:
        s.bind(("0.0.0.0", PORT))
    except OSError as e:
        log.critical("FATAL: port %d in use: %s", PORT, e)
        return 5
    finally:
        s.close()
    return 0


PORT = 8100


def main():
    global PORT
    if "--port" in sys.argv:
        PORT = int(sys.argv[sys.argv.index("--port") + 1])

    code = validate_startup()
    if code:
        sys.exit(code)

    # Re-read timeline if generate.py rewrote it (mtime check is in get(),
    # but log a line at startup so the log shows which generation we took).
    tl = TIMELINE.get()
    log.info("KaviTV relay %s starting on :%d (ffmpeg=%s)",
             VERSION, PORT, FFMPEG)
    log.info("channels: %s", sorted(tl["channels"].keys()))

    srv = ThreadingHTTPServer(("0.0.0.0", PORT), Handler)
    try:
        srv.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        log.info("shutting down, reaping %d children", len(CHILDREN._procs))
        CHILDREN.kill_all()
        srv.server_close()
        log.info("relay stopped")


if __name__ == "__main__":
    main()
